app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, abort, flash, request, \
    current_app, make_response
from . import main
from .. import db
from ..models import Departments, Subjects, Books, Posts


# show the main page
@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('main.html', departs=get_department_lists(),
                           last_books=get_list_of_books(6),
                           last_posts=get_list_of_posts())


@main.route('/department/')
@main.route('/department/<depart_>')
def view_departments_subjects(depart_=None):
    if depart_ is None:
        return render_template('departments.html', departs=get_department_lists())
    else:
        return render_template('subjects.html', departs=get_department_lists(),
                               subjects=get_subjects_lists_by_department(depart_))


@main.route('/subjects/<sub>')
def view_books_of_subject(sub=None):
    if sub is not None:
        return render_template('books.html', departs=get_department_lists(),
                               books=get_books_lists_by_subject(sub))


# to show news feed
@main.route('/blog/')
@main.route('/blog/<id>')
def blogs(id=None):
    if id and get_post_by_id(id) is not None:
        return render_template('post.html', departs=get_department_lists(),
                               post=get_post_by_id(id))
    else:
        return 'Not Found'


# to get department list from database
def get_department_lists():
    return Departments.query.order_by(Departments.id).all()


# to get subject list by department
def get_subjects_lists_by_department(department='GS'):
    return Subjects.query.filter_by(code_department=department).order_by(Subjects.id).all()


# to get books by its subject
def get_books_lists_by_subject(subject=None):
    if subject is not None:
        return Books.query.filter_by(code_subject=subject).all()


# get list of books by specific number of books
def get_list_of_books(limit=3):
    return Books.query.limit(limit).all()


# to get list of posts at main page
def get_list_of_posts(limit=4):
    return Posts.query.order_by(Posts.id.desc()).limit(limit).all()


# to get desired post to show it
def get_post_by_id(id=None):
    if id is not None:
        return Posts.query.filter_by(id=id).first()

app/templates/base.html
<!--
    Designed and Coded by : Ahmed Alkabir
-->

<!DOCTYPE html>
<html dir="rtl">
    {% block head %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="مكتبة الإلكترونية لكلية الهندسة صبراته" />
        <title>المكتبة الإلكترونية</title>


        <link rel="stylesheet" href="../static/css/uikit.min.css">
        <link rel="stylesheet" href="../static/css/main.css">
        <link rel="stylesheet" href="../static/css/default.css">
        <link rel="stylesheet" href="../static/css/font-awesome.min.css">
    </head>
    {% endblock %}
    <body id="bkg">

        <!-- preloader -->
        <div class="preloader"></div>

        <div class="uk-container uk-container-large box">
            <div class="logo">
                <img src="../static/img/logo.png">
            </div>
        </div>
        {% block navbar %}
        <nav class="uk-navbar-container" uk-navbar="mode: click" >
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav menu">
                    <li class="uk-parent"><a href="{{ url_for('main.index') }}">الرئيسية</a></li>
                    <li>
                        <a href="">أقسام المواد</a>
                        <div class="uk-navbar-dropdown">
                             <ul class="uk-nav uk-navbar-dropdown-nav">
                                 {% for depart in departs %}
                                 <li><a href="{{ url_for('.view_departments_subjects',depart_=depart.code_department) }}">{{ depart.name_department }}</a>
                                     {% endfor %}
                             </ul>
                        </div>
                    </li>
                    <li><a href="{{ url_for('main.blogs') }}">المدونة</a></li>
                </ul>
            </div>

             <div class="uk-navbar-left menu">
                <ul class="uk-navbar-nav">
                    <li class="uk-parent about"><button class="uk-button uk-button-primary"><a href=""></a>حول المشروع</button></li>
                </ul>
            </div>

            <div class="uk-navbar-container menu-toggle" uk-navbar>
                <div class="uk-navbar-left">
                    <a class="uk-navbar-toggle" uk-navbar-toggle-icon uk-toggle="target: #offcanvas-slide" href=""></a>
                </div>
            </div>
        </nav>
        <!-- side nav -->
        <div id="offcanvas-slide" uk-offcanvas="flip:true">
            <div class="uk-offcanvas-bar uk-flex uk-flex-column uk-text-center">

                <button class="uk-offcanvas-close uk-close-large" type="button" uk-close></button>

                    <ul class="uk-nav uk-nav-primary uk-nav-center uk-margin-auto-vertical uk-nav-parent-icon" uk-nav>
                         <li class="uk-active"><a href="#">الرئيسية</a></li>
                        <li class="uk-parent">
                            <a href="#">أقسام المواد</a>
                            <ul class="uk-nav-sub">
                                {% for depart in departs %}
                                <li><a href="{{url_for('.view_departments_subjects',depart_=depart.code_department)}}">{{ depart.name_department }}</a>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>

                    <div>
                        <div class="uk-grid-small uk-child-width-auto uk-flex-inline" uk-grid>
                            <div>
                                <a class="uk-icon-button" href="#" uk-icon="icon: facebook"></a>
                            </div>
                            <div>
                                <a class="uk-icon-button" href="#" uk-icon="icon: twitter"></a>
                            </div>
                         </div>
                    </div>

                </div>
            </div>
        </div>
        {% endblock %}
        {% block purpose_of_project%}
        <div class="uk-container uk-container-large info-project">
            <div class="uk-grid-medium uk-child-width-expand@s uk-text-center grid-ak " uk-grid>
                <div class="uk-card uk-card-default uk-card-body card-ak">
                    <i class="fa fa-book fa-5x"><h1>المكتبة الإلكترونية</h1></i>
                    <h4>مشروع المكتبة الإلكترونية حيث يستهدف طلبة كليات الهندسة بالمجمل
                        و نحاول أن نوفر أغلب المراجع الهندسية لطلبةالكليات الهندسية
                        والتقنية في محاولة تقليل من الجهد الطالب عن البحث عن المراجع </h4>
                </div>

                <div class="uk-card uk-card-default uk-card-body card-ak">
                    <i class="fa fa-pencil fa-5x"><h1>المدونة الطالب</h1></i>
                    <h4>لا يقف المشروع عند المكتبة بل أيضا نحاول نشر مقالات التي ترتبط بالطالب
                         في محاولة لمساعدة
                         الطالب في مشواره العلمي</h4>
                </div>
            </div>
        </div>
        {% endblock %}

        {% block container %}
        <div class="uk-container uk-container-large last-blogs">
            <div class="uk-grid-match uk-grid-small" uk-grid>
                <div class="uk-width-3-5@m uk-width-2-3@l">
                    <div class="uk-card uk-card-default uk-card-body card-ak">
                        <h2 class="last-blogs-title"><span>أخر مادون</span></h2>
                        {% block last_articles %}
                        {% endblock %}
                    </div>
                </div>
                <div class="uk-width-1-5@m uk-width-1-3@l uk-width-expand">
                    <div class="uk-card uk-card-default uk-padding uk-card-body card-ak">
                        <h2 class="last-blogs-title"><span>أخر الكتب المضافة</span></h2>
                        <div class="uk-grid-small uk-child-width-expand@s uk-grid">
                            {% block last_books %}
                            <div class="last-book items">
                                <article class="article-item uk-margin-top">
                                    <a href="" class="blog-item">
                                        <div class="uk-first-column">
                                            <a href=""><h1 class="title-blog uk-text-center">Numerical Methods With Matlab Applications</h1></a>
                                            <span class="uk-text-right uk-text-meta">القسم : </span>
                                            <span class="uk-text-right uk-text-meta uk-margin-left">الكهربائية والإتصاللات</span>
                                            <span class="uk-text-right uk-text-meta uk-margin-right">تاريخ الإضافة :</span>
                                            <span class="uk-text-right uk-text-meta">1/2/2001</span>
                                        </div>
                                    </a>
                                </article>
                                <article class="article-item uk-margin-top">
                                    <a href="" class="blog-item">
                                        <div class="uk-first-column">
                                            <a href=""><h1 class="title-blog uk-text-center">Digital Design Morris Mano 5th Edition</h1></a>
                                            <span class="uk-text-right uk-text-meta">القسم : </span>
                                            <span class="uk-text-right uk-text-meta uk-margin-left">الكهربائية والإتصاللات</span>
                                            <span class="uk-text-right uk-text-meta uk-margin-right">تاريخ الإضافة :</span>
                                            <span class="uk-text-right uk-text-meta">1/2/2001</span>
                                        </div>
                                    </a>
                                </article>
                                <article class="article-item uk-margin-top">
                                    <a href="" class="blog-item">
                                        <div class="uk-first-column">
                                            <a href=""><h1 class="title-blog uk-text-center">Digital Systems Principles and Applications</h1></a>
                                            <span class="uk-text-right uk-text-meta">القسم : </span>
                                            <span class="uk-text-right uk-text-meta uk-margin-left">الكهربائية والإتصاللات</span>
                                            <span class="uk-text-right uk-text-meta uk-margin-right">تاريخ الإضافة :</span>
                                            <span class="uk-text-right uk-text-meta">1/2/2001</span>
                                        </div>
                                    </a>
                                </article>
                            </div>
                            {% endblock %}
                        </div>
                    </div>
{#                    <div class="uk-card uk-card-default uk-padding uk-card-body card-ak">#}
{#                        <h2 class="last-blogs-title"><span>تابعنا</span></h2>#}
{#                        <div class="uk-grid-small uk-child-width-expand@s uk-grid">#}
{#                            <iframe class="uk-margin" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FBETA-GROUP-1239063602774641%2F&tabs=timeline&width=500&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId"#}
{#                                width="500" height="500"#}
{#                                style="border:none;overflow:hidden"#}
{#                                scrolling="no" frameborder="0"#}
{#                                allowTransparency="true"></iframe>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
        {% endblock %}
        <footer class="uk-container uk-container-large footer">
            <div class="uk-child-width-expand@s uk-text-center uk-margin-top grid-ak-footer" uk-grid>
                <div>
                    <h4 class="last-blogs-title"><span>مواقع صديقة</span></h4>
                    <ul class="uk-list">
                        <li>جامعة صبراته</li>
                        <li>وازرة التعليم العالي</li>
                    </ul>
                </div>
                <div>
                    <img class="uk-align-center logo-footer" src="../static/img/logo_footer.png">
                    <span class="logo-title-sbu">جامعة صبراته</span>
                </div>
                <div>
                    <h4 class="last-blogs-title"><span>القائم علي المشرع</span></h4>
                    <span class="span-font uk-text-large uk-text-center"> مشروع تطوعي من تنفيذ طلبة كلية الهندسة - جامعة صبراته </span>
                </div>
            </div>
            <div class="uk-align-center">
                <b><p class="author-of-site"> Made with <span style="color: #e25555; font-size: 1.2em;">&hearts;</span> by Ahmed Alkabir </p></b>
            </div>
        </footer>
        {% block js %}
        <script src="../static/js/jquery-3.3.1.min.js"></script>
        <script src="../static/js/uikit.min.js"></script>
        <script src="../static/js/main.js"></script>
        <script src="../static/js/uikit-icons.min.js"></script>
        {% endblock %}
    </body>

</html>

app/templates/books.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="../static/css/post.css">
{% endblock %}

{% block purpose_of_project%}
{% endblock %}

{% block container %}
<div class="uk-container uk-container-expand list-book">
    <div class="uk-section uk-section-secondary uk-light">
        <div class="uk-container">
            <ul class="uk-breadcrumb">
                <li><a href="#">الرئيسية</a></li>
            </ul>

            <div class="uk-overflow-auto">
                <table class="uk-table uk-table-striped uk-table-hover">
                    <thead>
                        <tr>
                            <th>أسم الكتاب</th>
                            <th>نوع الكتاب</th>
                            <th>حجم الكتاب</th>
                            <th>رابط التحميل</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for book in books %}
                        <tr>
                            <td>{{ book.name_book }}</td>
                            <td>{{ book.type_of_book }}</td>
                            <td>{{ book.size_of_book }}</td>
                            <td><a href="{{book.url_of_book}}">التحميل</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/departments.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="../static/css/post.css">
{% endblock %}

{% block purpose_of_project%}
{% endblock %}

{% block container %}
<div class="uk-container uk-container-expand list-book">
    <div class="uk-section uk-section-secondary uk-light">
        <div class="uk-container">
            <ul class="uk-breadcrumb">
                <li><a href="#">الرئيسية</a></li>
            </ul>

            <div class="uk-overflow-auto">
                <table class="uk-table uk-table-striped uk-table-hover">
                    <thead>
                    <tr>
                        <th>كود القسم</th>
                        <th>القسم</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for depart in departs %}
                    <tr>
                        <td><a href="{{url_for('.view_departments_subjects',depart_=depart.code_department)}}">{{ depart.code_department }}</a></td>
                        <td><a href="{{url_for('.view_departments_subjects',depart_=depart.code_department)}}">{{ depart.name_department }}</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}

{% block last_books %}
<div class="last-book items">
    {% for last_book in last_books %}
    <article class="article-item uk-margin-top">
        <a href="" class="blog-item">
            <div class="uk-first-column">
                <a href="{{ last_book.url_of_book }}"><h1 class="title-blog uk-text-center">{{ last_book.name_book }}</h1></a>
            </div>
        </a>
    </article>
    {% endfor %}
</div>
{% endblock %}

{% block last_articles %}
<div class="list-articles">
    {% for last_post in last_posts %}
        <div class="uk-grid-medium uk-child-width-expand@s uk-grid">
            <article class="article-item">
                <a href="/blog/{{ last_post.id }}" class="blog-item">
                    <div class="uk-first-column">
                        <img class="uk-align-center uk-align-right@m uk-margin-remove-adjacent" src="{{ last_post.image_post }}" width="350" alt="">
                        <h1 class="title-blog">{{ last_post.title_post }}</h1>
                        <p class="entry-details ">{{ strip_tags(last_post.content_post)|truncate(20, True) }}</p>
                        <a href=""><p class="author">الكاتب : {{ last_post.author_post }}</p></a>
                    </div>
                </a>
            </article>
        </div>
    {% endfor %}
    <div class="uk-grid-medium uk-child-width-expand@s uk-grid">
        <ul class="uk-pagination uk-flex-center" uk-margin>
            <li><a href="#"><span uk-pagination-previous></span></a></li>
            <li class="uk-active"><span>1</span></li>
            <li class="uk-disabled"><span>...</span></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#"><span uk-pagination-next></span></a></li>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="../static/css/post.css">
{% endblock %}

{% block purpose_of_project%}
{% endblock %}

{% block container %}

    <div class="uk-height-large uk-background-cover uk-overflow-hidden uk-light uk-flex uk-flex-top"
         style="background-image: url('{{ post.image_post }}')" >
    </div>
 <div class="uk-section uk-section-secondary uk-preserve-color">
            <div class="uk-container uk-container-large blog">
                <div class="uk-card uk-card-default uk-padding uk-card-body card-ak">
                    <div class="header-meta-data uk-margin-top">
                        <h1 class="uk-heading-primary">{{ post.title_post }}</h1>
                        <ul class="uk-breadcrumb">
                            <li><a href="#">الرئيسية</a></li>
                            <li><a href="#">المدونة</a></li>
                        </ul>

                        <div class="author-img">
                            <img alt src="" height="64" width="64">
                        </div>

                        <div class="author-info">
                            <a href="#" rel="author">{{ post.author_post }}</a>
                        </div>

                    </div>

                    <div class="uk-section article-section">
                            <div class="uk-container">
                                <span class="uk-text-lead">
                                    {{ post.content_post|safe }}
                                </span>
                            </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

app/templates/subjects.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="../static/css/post.css">
{% endblock %}

{% block purpose_of_project%}
{% endblock %}

{% block container %}
<div class="uk-container uk-container-expand list-book">
    <div class="uk-section uk-section-secondary uk-light">
        <div class="uk-container">
            <ul class="uk-breadcrumb">
                <li><a href="#">الرئيسية</a></li>
            </ul>

            <div class="uk-overflow-auto">
                <table class="uk-table uk-table-striped uk-table-hover">
                    <thead>
                        <tr>
                            <th>رمز المادة</th>
                            <th>اسم المادة</th>
                            <th>الوحدات</th>
                            <th>المتطلبات</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for subject in subjects %}
                        <tr>
                            <td><a href="{{ url_for('.view_books_of_subject', sub = subject.code_subject) }}">{{ subject.code_subject }}</a></td>
                            <td><a href="{{ url_for('.view_books_of_subject', sub = subject.code_subject) }}">{{ subject.name_subject }}</a></td>
                            <td>{{ subject.units_subject }}</td>
                            <td>{{ subject.prerequisites }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}